require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
