version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps

workflows:
  workflow:
    jobs:
      - build
